[minio]
server = "111.222.333.444:9000"
access_key = "your_minio_access_key"
secret = "your_minio_secret"
https = false

[pg]
server = "222.333.444.555"
port = 5432
username = "your_user_name"
password = "your_password"
database = "your_database"
